apiVersion: v1
kind: Pod
metadata:
  name: pod-lb
  labels: 
    app: lb-pod
spec:
  containers:
  - name: container
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: lb-svc
spec:
  selector:
    app: lb-pod
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 8080