apiVersion: v1
kind: Pod
metadata:
  name: lb-pod-1
  labels: 
    app: lb-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: container
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: lb-pod-2
  labels: 
    app: lb-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - name: container
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: svc-1
spec:
  selector:
    app: lb-pod
  type: NodePort
  ports:
  - port: 9000
    targetPort: 8080
    nodePort: 32568
# 모든 노드에 32568 포트가 kube-proxy에 의해 열리게 되고, 모든 node에서 해당 포트로 요청해보게 되면 위에 생성된 2개의 pod로 트래픽이 로드밸런싱 되는 것을 볼 수 있다.