apiVersion: v1
kind: Pod
metadata:
  name: k8s-nodejs-pod2
  labels: 
    app: hi-nodejs2
spec:
  containers:
  - name: nodejs-container
    image: dbgurum/k8s-kor:nodejs_test2
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hi-nodejs-svc
spec:
  selector:
    app: hi-nodejs2
  type: NodePort
  ports:
  - port: 8899
    targetPort: 8000