apiVersion: v1
kind: Pod
metadata:
  name: clusterip-pod
  labels: 
    app: cip-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: container
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  selector:
    app: cip-pod
  ports:
  - port: 9000
    targetPort: 8080