version: '3.3'
services: 
    elk:
        image: sebp/elk:671
        ports: 
            - "5601:5601" #kibana
            - "9200:9200" # elasticsearch
            - "5044:5044" # logstash
        restart: always
        environment: 
            - ES_JAVA_OPTS=-Xmx1g -Xms1g