apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod1
  namespace: dev-ns
  labels:
    app: dev-pod
spec:
  containers:
    - name: container01
      image: kubetm/app
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-svc1
  namespace: dev-ns
spec:
  selector:
    app: dev-pod
  ports:
    - port: 9090
      targetPort: 8080