# ResourceQuota namespace에 자원 총 할당량을 제한한다.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq1
  namespace: dev-ns
spec:
  hard: # 물리적인 영역 (해당 namespace에는 총 1G memory까지의 pod를 할당할 수 있다.)
    requests.memory: 1Gi
    limits.memory: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq2
  namespace: dev-ns
spec:
  hard: # 물리적인 영역 (해당 namespace에는 총 2개의 pod까지만 할당할 수 있다.)
    pods: 2
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod2
  namespace: dev-ns
spec:
  containers:
    - image: kubetm/app
      name: container1
      resources:
        requests:
          memory: 0.5Gi
        limits:
          memory: 0.5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod3
  namespace: dev-ns
spec:
  containers:
    - image: kubetm/app
      name: container1
      resources:
        requests:
          memory: 0.7Gi
        limits:
          memory: 0.7Gi

