apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pvc1-pod
spec:
  containers:
    - image: dbgurum/k8s-kor:nodejs_test2
      name: nodejs-container
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: testpath
          mountPath: /mount1
  volumes:
    - name: testpath
      persistentVolumeClaim:
        claimName: pvc1
