apiVersion: v1
kind: Pod
metadata:
  name: pod-vol1
spec:
  containers:
    - image: dbgurum/k8s-lab:initial
      name: container1
      volumeMounts:
        - name: empty-dir
          mountPath: /mount1
    - image: dbgurum/k8s-lab:initial
      name: container2
      volumeMounts:
        - name: empty-dir
          mountPath: /mount2
  volumes:
    - name: empty-dir
      emptyDir: {} 
---