apiVersion: v1
kind: Pod
metadata:
  name: pod-vol1
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
    - image: dbgurum/k8s-lab:initial
      name: container1
      volumeMounts:
        - name: host-path
          mountPath: /mount1
  volumes:
    - name: host-path
      hostPath:
        path: /data_dir
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-vol2
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
    - image: dbgurum/k8s-lab:initial
      name: container1
      volumeMounts:
        - name: host-path
          mountPath: /mount1
  volumes:
    - name: host-path
      hostPath:
        path: /data_dir
        type: DirectoryOrCreate
