apiVersion: v1
kind: Pod
metadata:
  name: ns-pod1
spec:
  nodeSelector:
   kubernetes.io/hostname: k8s-node1 # kubectl describe node {node} 해서 Labels:에 나오는 kubernetes.io 접두사가 붙은 라벨을 사용해야 한다.
  containers:
  - name: container1
    image: dbgurum/k8s-lab:initial