# 스케줄러에 의한 Node 스케줄링
apiVersion: v1
kind: Pod
metadata:
  name: ns-pod3
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: container1
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi