apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-loadbalancing
  annotations: 
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: svc-shopping
          servicePort: 8080
      - path: /customer
        backend:
          serviceName: svc-customer
          servicePort: 8080
      - path: /order
        backend:
          serviceName: svc-order
          servicePort: 8080
